// Mocks generated by Mockito 5.4.6 from annotations
// in bojang/test/screens/auth_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bojang/models/user.dart' as _i4;
import 'package:bojang/services/api_service.dart' as _i5;
import 'package:bojang/services/google_auth_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GoogleAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleAuthService extends _i1.Mock implements _i2.GoogleAuthService {
  MockGoogleAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isSignedIn =>
      (super.noSuchMethod(Invocation.getter(#isSignedIn), returnValue: false)
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.User?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i3.Future<_i4.User?>.value(),
          )
          as _i3.Future<_i4.User?>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.User?> signInSilently() =>
      (super.noSuchMethod(
            Invocation.method(#signInSilently, []),
            returnValue: _i3.Future<_i4.User?>.value(),
          )
          as _i3.Future<_i4.User?>);

  @override
  _i3.Future<bool> isSignedInToGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#isSignedInToGoogle, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i5.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> register({
    required String? email,
    required String? username,
    required String? password,
    required String? displayName,
    String? deviceId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #email: email,
              #username: username,
              #password: password,
              #displayName: displayName,
              #deviceId: deviceId,
            }),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<Map<String, dynamic>?> login({
    required String? email,
    required String? password,
    String? deviceId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #email: email,
              #password: password,
              #deviceId: deviceId,
            }),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<Map<String, dynamic>?> googleAuth({
    required String? googleId,
    required String? email,
    required String? displayName,
    String? profileImageUrl,
    String? idToken,
    String? accessToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#googleAuth, [], {
              #googleId: googleId,
              #email: email,
              #displayName: displayName,
              #profileImageUrl: profileImageUrl,
              #idToken: idToken,
              #accessToken: accessToken,
            }),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<Map<String, dynamic>?> getUserProgress() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProgress, []),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<List<Map<String, dynamic>>?> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i3.Future<List<Map<String, dynamic>>?>.value(),
          )
          as _i3.Future<List<Map<String, dynamic>>?>);

  @override
  _i3.Future<List<Map<String, dynamic>>?> getLevels(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getLevels, [categoryId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>?>.value(),
          )
          as _i3.Future<List<Map<String, dynamic>>?>);

  @override
  _i3.Future<List<Map<String, dynamic>>?> getQuestions(String? levelId) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestions, [levelId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>?>.value(),
          )
          as _i3.Future<List<Map<String, dynamic>>?>);

  @override
  _i3.Future<List<Map<String, dynamic>>?> getGames(String? levelId) =>
      (super.noSuchMethod(
            Invocation.method(#getGames, [levelId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>?>.value(),
          )
          as _i3.Future<List<Map<String, dynamic>>?>);

  @override
  _i3.Future<bool> submitQuizSession(Map<String, dynamic>? sessionData) =>
      (super.noSuchMethod(
            Invocation.method(#submitQuizSession, [sessionData]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> submitGameScore(Map<String, dynamic>? scoreData) =>
      (super.noSuchMethod(
            Invocation.method(#submitGameScore, [scoreData]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> updateStreak(Map<String, dynamic>? streakData) =>
      (super.noSuchMethod(
            Invocation.method(#updateStreak, [streakData]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<Map<String, dynamic>>?> getAchievements() =>
      (super.noSuchMethod(
            Invocation.method(#getAchievements, []),
            returnValue: _i3.Future<List<Map<String, dynamic>>?>.value(),
          )
          as _i3.Future<List<Map<String, dynamic>>?>);

  @override
  _i3.Future<List<Map<String, dynamic>>?> getUserAchievements() =>
      (super.noSuchMethod(
            Invocation.method(#getUserAchievements, []),
            returnValue: _i3.Future<List<Map<String, dynamic>>?>.value(),
          )
          as _i3.Future<List<Map<String, dynamic>>?>);

  @override
  _i3.Future<List<Map<String, dynamic>>?> getLeaderboard({
    required String? type,
    String? period,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLeaderboard, [], {
              #type: type,
              #period: period,
              #limit: limit,
            }),
            returnValue: _i3.Future<List<Map<String, dynamic>>?>.value(),
          )
          as _i3.Future<List<Map<String, dynamic>>?>);

  @override
  _i3.Future<bool> syncOfflineData(List<Map<String, dynamic>>? syncData) =>
      (super.noSuchMethod(
            Invocation.method(#syncOfflineData, [syncData]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, dynamic>?> getContentVersion() =>
      (super.noSuchMethod(
            Invocation.method(#getContentVersion, []),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<bool> isOnline() =>
      (super.noSuchMethod(
            Invocation.method(#isOnline, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
