// Mocks generated by Mockito 5.4.6 from annotations
// in bojang/test/screens/profile_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i8;

import 'package:bojang/models/user.dart' as _i4;
import 'package:bojang/services/google_auth_service.dart' as _i2;
import 'package:bojang/services/progress_service.dart' as _i5;
import 'package:flutter/material.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GoogleAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleAuthService extends _i1.Mock implements _i2.GoogleAuthService {
  MockGoogleAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isSignedIn =>
      (super.noSuchMethod(Invocation.getter(#isSignedIn), returnValue: false)
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.User?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i3.Future<_i4.User?>.value(),
          )
          as _i3.Future<_i4.User?>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.User?> signInSilently() =>
      (super.noSuchMethod(
            Invocation.method(#signInSilently, []),
            returnValue: _i3.Future<_i4.User?>.value(),
          )
          as _i3.Future<_i4.User?>);

  @override
  _i3.Future<bool> isSignedInToGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#isSignedInToGoogle, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [ProgressService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProgressService extends _i1.Mock implements _i5.ProgressService {
  MockProgressService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get currentStreak =>
      (super.noSuchMethod(Invocation.getter(#currentStreak), returnValue: 0)
          as int);

  @override
  int get longestStreak =>
      (super.noSuchMethod(Invocation.getter(#longestStreak), returnValue: 0)
          as int);

  @override
  List<DateTime> get playDates =>
      (super.noSuchMethod(
            Invocation.getter(#playDates),
            returnValue: <DateTime>[],
          )
          as List<DateTime>);

  @override
  Map<String, double> get categoryProgress =>
      (super.noSuchMethod(
            Invocation.getter(#categoryProgress),
            returnValue: <String, double>{},
          )
          as Map<String, double>);

  @override
  Map<String, int> get categoryScores =>
      (super.noSuchMethod(
            Invocation.getter(#categoryScores),
            returnValue: <String, int>{},
          )
          as Map<String, int>);

  @override
  List<String> get unlockedAchievements =>
      (super.noSuchMethod(
            Invocation.getter(#unlockedAchievements),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  int get totalQuizzesTaken =>
      (super.noSuchMethod(Invocation.getter(#totalQuizzesTaken), returnValue: 0)
          as int);

  @override
  int get totalCorrectAnswers =>
      (super.noSuchMethod(
            Invocation.getter(#totalCorrectAnswers),
            returnValue: 0,
          )
          as int);

  @override
  int get currentLevel =>
      (super.noSuchMethod(Invocation.getter(#currentLevel), returnValue: 0)
          as int);

  @override
  double get accuracy =>
      (super.noSuchMethod(Invocation.getter(#accuracy), returnValue: 0.0)
          as double);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i3.Future<void> updateQuizResults(
    String? category,
    int? score,
    int? totalQuestions, {
    _i6.BuildContext? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateQuizResults,
              [category, score, totalQuestions],
              {#context: context},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  String getAchievementTitle(String? achievementId) =>
      (super.noSuchMethod(
            Invocation.method(#getAchievementTitle, [achievementId]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#getAchievementTitle, [achievementId]),
            ),
          )
          as String);

  @override
  String getAchievementDescription(String? achievementId) =>
      (super.noSuchMethod(
            Invocation.method(#getAchievementDescription, [achievementId]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#getAchievementDescription, [achievementId]),
            ),
          )
          as String);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
